const users = [
  {
    id: 1,
    username: "Rukky",
    name: "Rukky",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 2,
    username: "Kindness",
    name: "Kindness",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 3,
    username: "Ife",
    name: "Ife",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 4,
    username: "Jadesola",
    name: "Jadesola",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 5,
    username: "Innocent",
    name: "Innocent",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 6,
    username: "Dominion",
    name: "Dominion",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 7,
    username: "Aaron",
    name: "Aaron",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 8,
    username: "Feranmi",
    name: "Feranmi",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 9,
    username: "Daniel",
    name: "Daniel",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 10,
    username: "Tomi",
    name: "Tomi",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 11,
    username: "Grace",
    name: "Grace",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 12,
    username: "Kevin",
    name: "Kevin",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 13,
    username: "Blessing",
    name: "Blessing",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 14,
    username: "Alex",
    name: "Alex",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 15,
    username: "Ifeoma",
    name: "Ifeoma",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 16,
    username: "Samuel",
    name: "Samuel",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 17,
    username: "Victor",
    name: "Victor",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 18,
    username: "Esther",
    name: "Esther",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 19,
    username: "Emeka",
    name: "Emeka",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
  {
    id: 20,
    username: "Nadia",
    name: "Nadia",
    bio: "Welcome to my profile.",
    pronouns: "",
    gender: "",
    profilePicture: "",
    links: [],
  },
];

export default users;